export default {
	localStorageKeys: {
		DATA_KEY: "DATA",
		THEME_KEY: "THEME",
		LANG_KEY: "LANG",
	},
	eventTypes: {
		COMBAT: "combat",
		ENCOUNTER: "encounter",
		DISCOVERY: "discovery",
		TRAVEL: "travel",
		OTHER: "other",
	},
	objectTypes: {
		ALL: "all",
		OBJECTIVE: "objective",
		EVENT: "event",
		LOCATION: "location",
		CHARACTER: "character",
		NOTE: "note",
	},
	seasons: {
		SPRING: "spring",
		SUMMER: "summer",
		AUTUMN: "autumn",
		WINTER: "winter",
	},
	icons: {
		objective: "mdi-star-circle",
		event: "mdi-sword-cross",
		location: "mdi-home",
		character: "mdi-account",
		note: "mdi-note-text",
		completed: "mdi-check-decagram",
		combat: "mdi-sword-cross",
		encounter: "mdi-account-group",
		discovery: "mdi-magnify",
		travel: "mdi-horseshoe",
		other: "mdi-help",
	},
};
